### PR TITLE
library build issue fixes

### PR DESCRIPTION
**Pull request by tsukhu**
-  Currently there are two issues
- common js builds marked as esmodule in some of the libs
- one of the files has a direct ".ts" import resulting in incorrect lib generation

This PR fixes these

### CODE REVIEW

**Comment by marcbuils** [comment]
Hi, the modules are pushed on npm in commonjs and esm, but the must be used in esm only, not in commonjs. 
The common JS builds are pushed on npm only for the lint, but musn't be built in a project.
It's why all modules are marked as module. This gives thé possibility to load other pin's dynamically in a space

**Comment by tsukhu** [comment]
aah ok .. :-)
then only the minor issue of the `menu-button-image.element.ts` is valid then

**Comment by marcbuils** [comment]
In fact you probably right about the package.json because esm modules use an oth package.esm.json
I check this point before to merge your PR ;)

**Comment by tsukhu** [comment]
remerged the changes to the new baseline version.

**Comment by marcbuils** [comment]
Thanks ! Your fixes are embeded in this commit:
https://github.com/pinser-metaverse/pinser-metaverse/commit/642af1f537b00a0fd63a612ee59259f36953740e

**Pull request closed without merging**
